### PR TITLE
Check data files in test.sh

### PR DESCRIPTION
**Pull request by szepeviktor**
Just that.
I think some of them does not exist.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Success 🍏 

```
ls: cannot access 'tests/data/block/*.json': No such file or directory
```

**Comment by szepeviktor** [comment]
@johnbillion Please merge this single line. It is very useful. Points out missing files.

**Comment by johnbillion** [comment]
I want to add this in 👍  but it causes the build to fail and I want to fix (add) the missing tests first

**Comment by johnbillion** [comment]
Ah I'll merge it and give myself some incentive to do it

**Pull request merged**
