### PR TITLE
Use features of find command in test.sh

### PR DESCRIPTION
**Pull request by szepeviktor**
`find schemas/ -type f -name "*.json" -not -path "$file" -printf ' -r %p'`

And break ajv options to separate lines.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@johnbillion Friendly ping 🏓

**Comment by szepeviktor** [comment]
@johnbillion This PR seems to be an anti-john one.

**Comment by johnbillion** [comment]
On my local machine I get an error when running `composer test` with this change:

```
find: -printf: unknown primary or operator
```

I can't see an advantage to this change. The current code works fine as it is.

**Comment by szepeviktor** [comment]
All right. I am not a businessman but a little scientist.

> The -printf option is not in POSIX [find](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html). It is a feature of GNU [find](http://www.gnu.org/software/findutils/manual/html_mono/find.html#Print-File-Information), e.g., on Linux.

**Pull request closed without merging**
